num1 = float(input("Введите первое число: "))
num2 = float(input("Введите второе число: "))

print(f"Сложение: {num1 + num2}")
print(f"Вычитание: {num1 - num2}")
print(f"Умножение: {num1 * num2}")
print(f"Деление: {num1 / num2}")
print(f"Деление с остатком: {num1 % num2}")
print(f"Деление нацело: {num1 // num2}")
print(f"Возведение в степень: {num1 ** num2}")